pipeline{
    agent any
    tools{nodejs 'node'}
    stages{
        stage('software installations and git cloning'){
        steps{ git 'https://github.com/anishadaniels/gallery.git'
        sh 'npm install'
        sh 'npm install --save express'
        sh 'npm install -- global yarn'
         
        }
        }
       
    
        stage('Build'){
            steps{
                echo'build succesful'
            }
        }
        stage('Tests'){
            steps {
                sh 'npm test'}
        }
        stage('deploy to render'){
            steps{
                httpRequest httpMode: 'POST', responseHandle: 'NONE', url: 'https://api.render.com/deploy/srv-cfpodbarrk0fd9vgapqg?key=mK7t1pfKCkQ', wrapAsMultipart: false
                echo 'Deploy to render was succesful'
                 slackSend channel: 'anisha_ip1', message: "For build  ${env.JOB_NAME} build ${env.BUILD_ID}  the site is live at https://gallery-gt7q.onrender.com"
                
            }
        }


    }
}